#jdk:
#  - openjdk11

before_install:
  - source install-jdk.sh --feature 14
  - jshell --version

install:
  - unset JAVA_TOOL_OPTIONS
  - VERSION=$(java src/bach/Version.java)
  - if [[ $VERSION =~ ^.*-ea$ ]]; then java src/bach/Version.java ${VERSION}+${GIT_COMMIT:0:7}; fi
  - VERSION=$(java src/bach/Version.java)
  - echo "VERSION=${VERSION}"
  - java --show-version .bach/src/build/build/Bootstrap.java
  - INSTALL=--batch-mode --no-transfer-progress install:install-file
  - for files in .bach/workspace/deploy/maven/*.files ; do mvn ${INSTALL} $(cat ${files}) ; done
