#jdk:
#  - openjdk11

before_install:
  - source install-jdk.sh --feature 14
  - jshell --version

install:
  - unset JAVA_TOOL_OPTIONS
  - VERSION=$(java src/bach/Version.java)
  - if [[ $VERSION =~ ^.*-ea$ ]]; then java src/bach/Version.java ${VERSION}+${GIT_COMMIT:0:7}; fi
  - VERSION=$(java src/bach/Version.java)
  - MODULE_AND_VERSION="de.sormuras.bach@${VERSION}"
  - echo "MODULE_AND_VERSION=${MODULE_AND_VERSION}"
  - java --show-version .bach/src/build/build/Bootstrap.java
  - OUT=".bach/workspace"
  - POM_FILE="-DpomFile=src/de.sormuras.bach/main/maven/pom.xml"
  - JAR_FILE="-Dfile=${OUT}/modules/${MODULE_AND_VERSION}.jar"
  - SRC_FILE="-Dsources=${OUT}/sources/${MODULE_AND_VERSION}-sources.jar"
  - API_FILE="-Djavadoc=${OUT}/documentation/bach@${VERSION}-api.jar"
  - mvn --batch-mode --no-transfer-progress install:install-file ${POM_FILE} ${JAR_FILE} ${SRC_FILE} ${API_FILE}
