#jdk:
#  - openjdk11

before_install:
  - source install-jdk.sh --feature 14
  - jshell --version

install:
  - unset JAVA_TOOL_OPTIONS
  - VERSION=$(java src/bach/Version.java)
  - if [[ $VERSION =~ ^.*-ea$ ]]; then java src/bach/Version.java ${VERSION}+${GIT_COMMIT:0:7}; fi
  - VERSION=$(java src/bach/Version.java)
  - MODULE_AND_VERSION="de.sormuras.bach@${VERSION}"
  - echo "MODULE_AND_VERSION=${MODULE_AND_VERSION}"
  - java --show-version .bach/src/build/build/Bootstrap.java
  - FILES=$(cat .bach/workspace/deploy/maven/${MODULE_AND_VERSION}.files)
  - mvn --batch-mode --no-transfer-progress install:install-file ${FILES}
