jdk:
  - openjdk11

install:
  - unset JAVA_TOOL_OPTIONS
  - VERSION=$(java src/bach/Version.java)
  - if [[ $VERSION =~ ^.*-ea$ ]]; then java src/bach/Version.java ${VERSION}-${GIT_COMMIT}; fi
  - java src/bach/Version.java
  - java src/bach/Bootstrap.java
  - jshell .bach/out/maven-install.jsh
