name: Bach.java
on: push
jobs:
  build:
    name: "${{ matrix.os }} + Java ${{ matrix.java }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [11]
    runs-on: ${{ matrix.os }}
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: 'Cache Maven repository'
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-${{ matrix.java }}-maven-
    - name: 'Build with Bach.java'
      run: |
        java src/bach/Bootstrap.java
        source .bach/out/maven-install.sh
  jshell:
    name: 'jshell https://bit.ly/bach-jsh'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 'Invoke Bach.java via JShell'
      run: cd demo && jshell https://bit.ly/bach-jsh
