name: Minimal
on: push
jobs:
  bach:
    name: "Bach.java"
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 'Let Bach.java build the project'
      working-directory: doc/comparison/minimal/bach
      run: |
        find . -type f | wc -l
        du -bs .
        jshell https://bit.ly/bach-build
        du -bs .
  bach-11:
    name: "src/.bach-11/Bach.java"
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Launch Bach.java`s default build program (src/.bach-11)'
        working-directory: doc/comparison/minimal/bach
        run: |
          find . -type f | wc -l
          du -bs .
          java src/.bach-11/Bach.java build
          du -bs .
  maven:
    name: "Maven"
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 'Let Maven build the project'
      working-directory: doc/comparison/minimal/maven
      run: |
        find . -type f | wc -l
        du -bs .
        ./mvnw verify
        du -bs .
    - name: 'Size of ~/.m2'
      run: |
        find ~/.m2 -type f | wc -l
        du -bs ~/.m2
  gradle:
    name: "Gradle"
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 'Let Gradle build the project'
      working-directory: doc/comparison/minimal/gradle
      run: |
        find . -type f | wc -l
        du -bs .
        ./gradlew build
        du -bs .
    - name: 'Size of ~/.gradle'
      run: |
        find ~/.gradle -type f | wc -l
        du -bs ~/.gradle
