name: Bach.java
on: push
jobs:
  build:
    name: "Build (JDK-${{ matrix.java }}, ${{ matrix.os }})"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [11]
    runs-on: ${{ matrix.os }}
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: 'Set up JUnit Platform'
      uses: sormuras/setup-junit@master
      id: junit
      with:
        platform-version: '1.6.0'
    - name: 'Compile and run tests'
      run: |
        javac -d classes --class-path ${{ steps.junit.outputs.standalone-jar }} src/.bach-11/Bach.java $(find src/test -name "*.java")
        java -jar ${{ steps.junit.outputs.standalone-jar }} --class-path classes --scan-class-path
    - name: 'Build project: jigsaw.quick.start.with.tests'
      working-directory: doc/project/jigsaw.quick.start.with.junit
      run: java -Debug $GITHUB_WORKSPACE/src/.bach-11/Bach.java build
    - name: 'Upload summaries'
      uses: actions/upload-artifact@v1
      with:
        name: summary-jigsaw.quick.start.with.junit.md
        path: doc/project/jigsaw.quick.start.with.junit/.bach/summary.md
