name: Bach.java
on: push
jobs:
  build:
    name: "${{ matrix.os }} + Java ${{ matrix.java }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [11, 13]
    runs-on: ${{ matrix.os }}
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: 'Build Bach.java'
      run: java src/bach/Build.java
    - name: 'Build test projects'
      run: cd ${GITHUB_WORKSPACE}/src/test-project/alpha && java -Debug ${GITHUB_WORKSPACE}/src/bach/Bach.java build
