name: Bach.java
on: push
jobs:
  build:
    name: "${{ matrix.os }} + Java ${{ matrix.java }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [11, 13]
    runs-on: ${{ matrix.os }}
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: 'Show Bach.java version'
      run: java src/build/Version.java
    - name: 'Build Bach.java'
      run: jshell --show-version build.jsh
    - name: 'Install modules into local Maven repository'
      if: matrix.os != 'windows-latest'
      run: source bin/maven-install.sh
    - name: 'Install modules into local Maven repository'
      if: matrix.os == 'windows-latest'
      run: bin/maven-install.bat
