name: Bach.java
on: push
jobs:
  build:
    name: "Build (JDK-${{ matrix.java }}, ${{ matrix.os }})"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [14, 15-ea]
    runs-on: ${{ matrix.os }}
    steps:
    - name: 'Checkout sources'
      uses: actions/checkout@v2
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: 'Build Bach.java'
      run: java --show-version .bach/src/build/build/Bootstrap.java
    - name: 'Upload build artifact'
      uses: actions/upload-artifact@v2
      with:
        name: artifact-${{ matrix.java }}-${{ matrix.os }}
        path: .bach/workspace/summary.md
