name: bach-doc-comparison
on: push
jobs:
  bach:
    name: "Bach.java"
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 'Let Bach.java build the project'
      working-directory: doc/comparison/minimal/bach
      run: |
        find . -type f | wc -l
        du -hs .
        jshell https://bit.ly/bach-build
        du -hs .
  maven:
    name: "Maven"
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 'Let Maven build the project'
      working-directory: doc/comparison/minimal/maven
      run: |
        find . -type f | wc -l
        du -hs .
        mvn verify
        du -hs .
    - name: 'Size of Maven and ~/.m2'
      run: |
        find $M2_HOME -type f | wc -l
        du -hs $M2_HOME
        find ~/.m2 -type f | wc -l
        du -hs ~/.m2
  gradle:
    name: "Gradle"
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 'Let Gradle build the project'
      working-directory: doc/comparison/minimal/gradle
      run: |
        find . -type f | wc -l
        du -hs .
        ./gradlew build
        du -hs .
    - name: 'Size of ~/.gradle'
      run: |
        find ~/.gradle -type f | wc -l
        du -hs ~/.gradle
