name: Changelog
on:
  push:
    paths:
      - '.github/workflows/changelog.yml'
  issues:
    types: [closed]
  milestone:
    types: [closed]
jobs:
  generate_changelog:
    name: 'Generate changelog'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout sources'
      uses: actions/checkout@v2
    - name: 'Generate changelog'
      uses: charmixer/auto-changelog-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        since_tag: '11.1'
    - name: 'Print changelog'
      run: cat CHANGELOG.md
