name: Demo

on: push

defaults:
  run:
    shell: bash --noprofile --norc -e -o pipefail -o xtrace {0}

jobs:
  build:
    name: 'Generate and build demos'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout sources'
      uses: actions/checkout@v2
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: 15-ea

    - name: 'Bach.java - Demo 0 - Simplicissimus'
      run: |
        jshell src/bach/bach-demo-0.jsh
        cd bach-demo-0-simplicissimus
        jshell https://sormuras.de/bach/build
        ./.bach/workspace/image/bin/java --list-modules

    - name: 'Bach.java - Demo 1 - Jigsaw Greetings!'
      run: |
        jshell src/bach/bach-demo-1.jsh
        cd bach-demo-1-jigsaw-greetings
        jshell https://sormuras.de/bach/build
        java --module-path ./.bach/workspace/classes --module com.greetings/com.greetings.Main
        java --module-path ./.bach/workspace/modules --module com.greetings
        ./.bach/workspace/image/bin/java --list-modules
        ./.bach/workspace/image/bin/greetings

    - name: 'Bach.java - Demo 2 - Jigsaw Greetings World!'
      run: |
        jshell src/bach/bach-demo-2.jsh
        cd bach-demo-2-jigsaw-greetings-world
        jshell https://sormuras.de/bach/build
        java --module-path ./.bach/workspace/classes --module com.greetings/com.greetings.Main
        java --module-path ./.bach/workspace/modules --module com.greetings
        ./.bach/workspace/image/bin/java --list-modules
        ./.bach/workspace/image/bin/greetings

    - name: 'Bach.java - Demo 99 - Luftballons'
      run: |
        jshell src/bach/bach-demo-99.jsh
        cd bach-demo-99-balloons
        jshell https://sormuras.de/bach/build
        ./.bach/workspace/image/bin/java --list-modules
