name: Demo

on: push

defaults:
  run:
    shell: bash --noprofile --norc -e -o pipefail -o xtrace {0}

jobs:
  build:
    name: 'Generate and build demos'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout sources'
      uses: actions/checkout@v2
    - name: 'Download JDK 16'
      uses: sormuras/download-jdk@v1
      with:
        feature: 16
    - name: 'Setup JDK'
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JDK_VERSION }}
        jdkFile: ${{ env.JDK_FILE }}

    - name: 'Bach.java - Demo 0 - Simplicissimus'
      run: |
        jshell https://sormuras.de/bach/demo-0
        cd bach-demo-0-simplicissimus
        jshell https://sormuras.de/bach/build
        ./.bach/workspace/image/bin/java --list-modules

    - name: 'Bach.java - Demo 1 - Jigsaw Greetings!'
      run: |
        jshell https://sormuras.de/bach/demo-1
        cd bach-demo-1-jigsaw-greetings
        jshell https://sormuras.de/bach/build
        java --module-path ./.bach/workspace/modules --module com.greetings
        ./.bach/workspace/image/bin/java --list-modules
        ./.bach/workspace/image/bin/bach-demo-1-jigsaw-greetings

    - name: 'Bach.java - Demo 2 - Jigsaw Greetings World!'
      run: |
        jshell https://sormuras.de/bach/demo-2
        cd bach-demo-2-jigsaw-greetings-world
        jshell https://sormuras.de/bach/build
        java --module-path ./.bach/workspace/modules --module com.greetings
        ./.bach/workspace/image/bin/java --list-modules
        ./.bach/workspace/image/bin/bach-demo-2-jigsaw-greetings-world

    - name: 'Bach.java - Demo 99 - Luftballons'
      run: |
        jshell https://sormuras.de/bach/demo-99
        cd bach-demo-99-balloons
        jshell https://sormuras.de/bach/build
        ./.bach/workspace/image/bin/java --list-modules
