name: Documentation
on:
  push:
    paths:
      - '.github/workflows/documentation.yml'
      - 'doc/**'
jobs:
  build:
    name: "Build projects"
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout sources'
      uses: actions/checkout@v2
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: 15-ea

    - name: 'Build Jigsaw Quick-Start (direct)'
      run: java doc/src/BuildJigsawQuickStart.java

    - name: 'Build Jigsaw Quick-Start (jshell)'
      working-directory: doc/project/JigsawQuickStart
      run: jshell -R-Debug ${GITHUB_WORKSPACE}/src/bach/bach-build.jsh

    - name: 'Build Jigsaw Quick-Start World (direct)'
      run: java doc/src/BuildJigsawQuickStartWorld.java

    - name: 'Build Jigsaw Quick-Start World (jshell)'
      working-directory: doc/project/JigsawQuickStart
      run: jshell -R-Debug ${GITHUB_WORKSPACE}/src/bach/bach-build.jsh
