name: Java Get.java CI

on: [push]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    container: openjdk:11
    steps:
    - uses: actions/checkout@v1
    - name: Print Java version
      run: java --version
    - name: Smoke tests
      run: |
        java -Debug=true src\bach\Get.java https://repo1.maven.org/maven2/junit/junit/3.7/junit-3.7.jar
        java -Debug=true src\bach\Get.java https://repo1.maven.org/maven2/junit/junit/3.7/junit-3.7.jar
