name: Dry-run `install-jdk.sh`

on:
  push:
    paths:
      - '.github/workflows/install-jdk-tests.yml'
      - 'install-jdk.properties'
      - 'install-jdk.sh'
  schedule:
    - cron:  '0 1 * * *'

defaults:
  run:
    shell: bash --noprofile --norc -e -o pipefail -o xtrace {0}

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./install-jdk.sh --dry-run --feature 15 --os linux-x64
      - run: ./install-jdk.sh --dry-run --feature 15 --os osx-x64
      - run: ./install-jdk.sh --dry-run --feature 15 --os windows-x64
