name: Test `install-jdk.sh`

on:
  push:
    paths:
    - '.github/workflows/install-jdk-tests.yml'
    - 'install-jdk.sh'
    - 'install-jdk-tests.sh'

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run
      run: ./install-jdk-tests.sh
