name: Test `install-jdk.sh`

on:
  push:
    paths:
    - '.github/workflows/install-jdk-tests.yml'
    - 'install-jdk.sh'
    - 'install-jdk-tests.sh'
  schedule:
    - cron:  '0 1 * * *'

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run
      run: ./install-jdk-tests.sh
