name: JDK

on:
  push:
    paths:
      - '.github/workflows/jdks.yml'

jobs:

  defaults:
    runs-on: ubuntu-latest
    steps:
      - uses: sormuras/download-jdk@master
      - uses: actions/setup-java@v1
        with:
          java-version: "${{ env.JDK_VERSION }}"
          jdkFile: "${{ env.JDK_FILE }}"
      - run: java -version
