name: JDK

on:
  
  push:
    paths:
    - '.github/workflows/jdks.yml'
    - 'install-jdk.sh'

jobs:
  
  jdk-ea:
    runs-on: ubuntu-latest
    steps:
    - run: wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
    - run: wget https://download.java.net/java/early_access/jdk15/1/GPL/openjdk-15-ea+1_linux-x64_bin.tar.gz --output-document jdk.tar.gz
    - uses: actions/setup-java@v1
      with:
        java-version: '15-ea'
        jdkFile: jdk.tar.gz
    - run: java -version

  jdk-6:
    if: 0 == 1
    runs-on: ubuntu-latest
    steps:
    - run: wget http://igm.univ-mlv.fr/~forax/tmp/jdk/jdk-6u45-linux-x64.tar.gz
    - uses: actions/setup-java@v1
      with:
        java-version: '1.6'
        jdkFile: jdk-6u45-linux-x64.tar.gz
    - run: java -version

  jdk-5:
    if: 0 == 1
    runs-on: ubuntu-latest
    steps:
    - run: wget http://igm.univ-mlv.fr/~forax/tmp/jdk/jdk1.5.0_22.tar.gz
    - uses: actions/setup-java@v1
      with:
        java-version: '1.5.0'
        architecture: x86
        jdkFile: jdk1.5.0_22.tar.gz
    - run: java -version
