name: Lib.java

on: [push]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
    - name: Print working directory
      run: pwd
    - name: Print Java version
      run: java --version
    - uses: actions/checkout@v1
    - name: Load module org.junit.jupiter version 5.5.1
      run: mkdir bin && cd bin && java ${GITHUB_WORKSPACE}/src/bach/Lib.java org.junit.jupiter@5.5.1
    - name: Load required modules of demo project
      run: cd ${GITHUB_WORKSPACE}/demo && java ${GITHUB_WORKSPACE}/src/bach/Lib.java
