name: Release

on:
  milestone:
    types: closed

jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: 'Checkout project'
      uses: actions/checkout@v1
    - name: 'Attach git to origin with write access'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout master
        git remote rm origin
        git remote add origin "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
    - name: 'Stash current version'
      run: |
        mkdir --parents bin
        echo $(java src/build/Version.java) > bin/VERSION
    - name: 'Set version to ${{ github.event.milestone.title }}'
      run: java src/build/Version.java ${{ github.event.milestone.title }}
    - name: 'Build ${GITHUB_REPOSITORY}'
      run: ./build.jsh
    - name: 'Commit all changed files, tag, and push origin'
      run: |
        git commit --all --message "Release ${{ github.event.milestone.title }}"
        git tag ${{ github.event.milestone.title }}
        git push origin master --tags
    - name: 'Create release'
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.milestone.title }}
        release_name: Release ${{ github.event.milestone.title }}
        draft: false
        prerelease: false
    - name: 'Restore previous version from bin/VERSION'
      run: |
        java src/build/Version.java $(<bin/VERSION)
        git commit --all --message "Back to development of version $(<bin/VERSION)"
        git push origin master
    - name: 'Deploy (bintray)'
      run: |
        mkdir --parents ~/.m2
        echo "<settings><servers><server><id>bintray</id><username>sormuras</username><password>${BINTRAY_KEY}</password></server></servers></settings>" > ~/.m2/settings.xml
        cat bin/maven-deploy-bintray.sh
        mvn --batch-mode -X org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy-file -DrepositoryId=bintray -Durl=https://api.bintray.com/maven/sormuras/maven/bach/;publish=0 -DpomFile=src\modules\de.sormuras.bach\main\maven\pom.xml -Dfile=bin\realm\main\modules\de.sormuras.bach-${{ github.event.milestone.title }}.jar -Dsources=bin\realm\main\de.sormuras.bach-${{ github.event.milestone.title }}-sources.jar -Djavadoc=bin\realm\main\bach-${{ github.event.milestone.title }}-javadoc.jar
